export default function AdminDashboard() {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-bold text-gray-900">Dashboard</h1>
      </div>
      
      {/* Stats Grid */}
      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
        <div className="bg-white p-6 rounded-lg shadow">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-medium text-gray-500">Total Users</h3>
          </div>
          <div className="mt-2">
            <div className="text-3xl font-bold text-gray-900">0</div>
            <p className="text-xs text-gray-500">No users yet</p>
          </div>
        </div>
        
        <div className="bg-white p-6 rounded-lg shadow">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-medium text-gray-500">Active Sessions</h3>
          </div>
          <div className="mt-2">
            <div className="text-3xl font-bold text-gray-900">1</div>
            <p className="text-xs text-gray-500">Your current session</p>
          </div>
        </div>
        
        <div className="bg-white p-6 rounded-lg shadow">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-medium text-gray-500">System Status</h3>
          </div>
          <div className="mt-2">
            <div className="text-3xl font-bold text-green-600">Online</div>
            <p className="text-xs text-gray-500">All systems operational</p>
          </div>
        </div>
        
        <div className="bg-white p-6 rounded-lg shadow">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-medium text-gray-500">Last Updated</h3>
          </div>
          <div className="mt-2">
            <div className="text-3xl font-bold text-gray-900">Now</div>
            <p className="text-xs text-gray-500">Real-time data</p>
          </div>
        </div>
      </div>
      
      {/* Welcome Card */}
      <div className="bg-white p-6 rounded-lg shadow">
        <h2 className="text-xl font-semibold text-gray-900 mb-2">Welcome to {{APP_NAME}}</h2>
        <p className="text-gray-600 mb-4">
          Your admin panel is ready to use. Start by customizing this dashboard or adding new features.
        </p>
        <div className="text-sm text-gray-600">
          <p className="mb-2">This admin panel was generated by ShadPanel. You can:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Add new pages in the <code className="bg-gray-100 px-1 rounded">app/admin/</code> directory</li>
            <li>Customize the layout in <code className="bg-gray-100 px-1 rounded">app/admin/layout.tsx</code></li>
            <li>Add authentication logic as needed</li>
            <li>Style with Tailwind CSS classes</li>
          </ul>
        </div>
      </div>
    </div>
  );
}